[tool.black]
line-length = 90

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = "(tests\\/\\.*)|(scratch\\.py)"

[[tool.mypy.overrides]]
module = "smart_open.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "digdag.*"
disallow_untyped_calls = false


[tool.ruff]
select = ["ALL", "PT"]
target-version = "py311"
exclude = [
    "digdag/utils/dagascii.py",
    "scratch.py"
]

ignore = [
    "ANN101",
    "ANN102",
    "ANN204",
    "COM812",
    "D107",
    "N812",
    "PTH",
    "C90",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D200",
    "D212",
    "D415",
    "EM101",
    "G004",
    "PD901",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "S320",
    "S321",
    "SLF001",
    "TD002",
    "TD003"
]

# allow autofix behavior for specified rules
fixable = ["E", "F", "I", "Q"]

# set max line length
line-length = 90

# enumerate all fixed violations
show-fixes = true

[tool.ruff.flake8-annotations]
mypy-init-return = true

[tool.ruff.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.per-file-ignores]
"tests/**/*" = [
    "ANN",
    "ARG001",
    "S101",
]

[tool.ruff.pycodestyle]
max-doc-length = 90

[tool.ruff.pydocstyle]
convention = "google"

[tool.coverage.run]
omit = [
    "digdag/utils/dagascii.py"
]
